#!/usr/bin/expect -f
set force_conservative 0
if {$force_conservative} {
set send_slow {1 .1}
proc send {ignore arg} {
sleep .1
exp_send -s -- $arg
}
}
set timeout -1
spawn telnet localhost 1977
match_max 100000
expect -exact "Trying 127.0.0.1...\r
Connected to localhost.\r
Escape character is '^]'.\r
Connected to emulated Apple\r
\r\r
D-DIAL #49\r\r
\r\r
  LOGIN\r\r
\r\r
 -->"
send -- "912 539 157\r"
expect -exact "912 539 157\r
*** *** ***\r\r\r00005 Calls / 004 Today\r\r}-->. +^#1T2=Remote:#912\r"
send -- ""
set telnet1 $spawn_id
spawn telnet 127.0.0.1 2977
match_max 100000
expect -exact "Trying 127.0.0.1...\r
Connected to 127.0.0.1.\r
Escape character is '^'.\r
Connected to emulated Apple\r
\r\r
D-DIAL #49\r\r
\r\r
LOGIN\r\r
\r\r
-->"
send -- "912 539 157\r"
expect -exact "912 539 157\r
*** *** ***\r\r\r00005 Calls / 004 Today\r\r}-->. +^#1[T2=Remote:#912\r"
send -- ""
set telnet2 $spawn_id
log_user 1
while {1} {
expect {
-i $telnet1 eof { break }
-i $telnet1 -re ".+" {
send -i $telnet2 -- $expect_out(buffer)
exp_continue
}
-i $telnet2 eof { break }
-i $telnet2 -re ".+" {
send -i $telnet1 -- $expect_out(buffer)
exp_continue
}
}
}
close -i $telnet1
close -i $telnet2
