#!/usr/bin/expect -f

log_user 0

# Spawn first telnet session
spawn telnet 127.0.0.1 1977
expect "Apple"
expect "LOGIN"
expect -- "-->"
send "912539157\r"
set tel1 $spawn_id

# Spawn second telnet session
spawn telnet 127.0.0.1 2977
expect "Apple"
expect "LOGIN"
expect -- "-->"
send "912539157\r"
set tel2 $spawn_id

# Bridge the two sessions: forward output from one to input of the other bidirectionally
while {1} {
    expect {
        -i $tel1 eof { break }
        -i $tel2 eof { break }
        -i $tel1 -re . {
            send -i $tel2 -- $expect_out(buffer)
            exp_continue
        }
        -i $tel2 -re . {
            send -i $tel1 -- $expect_out(buffer)
            exp_continue
        }
    }
}

close -i $tel1
close -i $tel2
